### ISSUE TITLE
Bad Request response comes from datastore is not so informative for investigating 

### ISSUE THREAD

**Issue by onurdialpad** [talkiq/gcloud-aio#126]
when something is wrong with our datastore query, gcloud only returns 400 with no meaningful logs. when we try to execute same query on https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/runQuery try window it tells me what is wrong with the query. it is not a bug but would be better if we have more information in the response we get.

**Comment by AlwxSin** [comment]
Definitely need more info. Google has meaningful errors - https://cloud.google.com/storage/docs/xml-api/reference-status#400%E2%80%94bad-request

But `gcloud-aio` simply do `resp.raise_for_status()` and I can't see body of response.

**Comment by TheKevJames** [comment]
Yeah, the big issue here is that the `aiohttp` library does not include the body when `raise_for_status` is called on a response (which is unfortunately different from `requests` :(). The recommended solution is to do:
```python
# resp = ...
try:
    resp.raise_for_status()
except aiohttp.ClientResponseError:
    logger.exception('Error body: %s', await resp.json())
    raise

return await resp.json()
```
but unfortunately that doesn't play very nicely with the Google API and how we do requests, since their APIs don't _all_ return JSON blobs and we try to use a single set of HTTP code for all libraries to make codegen easier.

To fit with our existing system, I suppose we could do:
```python
try:
    resp.raise_for_status()
except aiohttp.ClientResponseError:
    logger.exception('Error body: %s', await resp.text())
    raise
```
instead, which would at least get the body printed to the logs even if it's not very well-formatted (eg. text rather than JSON). I wonder if that solution would be enough to help solve the issues y'all are facing?

**Comment by AlwxSin** [comment]
@TheKevJames yeah, `resp.text` should be enough. At least, we can find this text in logs, since errors are rare.

Thank you.

**Comment by TheKevJames** [comment]
Alright, makes sense to me! I'll toss this on my backlog and see when I can get to it -- but I'd be happy to accept a PR to help speed things up, of course!
