### ISSUE TITLE
Datastore methods don't return the mutations results

### ISSUE THREAD

**Issue by yjaaidi** [talkiq/gcloud-aio#142]
AFAIK, it doesn't seem possible to retrieve the mutations results when using `insert`... or `operate` or `commit`.

It looks like there are some return statements missing here and there:

https://github.com/talkiq/gcloud-aio/blob/18612a995942dfc789cabe9d50549897330b0e9d/datastore/gcloud/aio/datastore/datastore.py#L375

https://github.com/talkiq/gcloud-aio/blob/18612a995942dfc789cabe9d50549897330b0e9d/datastore/gcloud/aio/datastore/datastore.py#L188

Let me know if I can help with a PR

**Comment by TheKevJames** [comment]
@yjaaidi you are indeed correct -- we've tended to want to return objects rather than raw response payloads in this library, as most usage seems to be following an ORM-like framework here. What sort of usecase do you have for getting the raw mutations back?

We'd be happy to accept a PR here to expose this data! If there's anything we should be doing to provide easier functionality here (say, a `gcloud.aio.datastore.Mutation` class), we'd be happy to accept a PR along those lines as well.

(sorry for the late response on this -- I seem to have disabled notifications on new issues on this repo; should be fixed now!)

**Comment by AlexisH** [comment]
Most basic usecase is to retrieve the ID of the newly inserted entity when we let the datastore automatically allocate it.
Is there another way to retrieve it ?

**Comment by AlexisH** [comment]
As the `Datastore` interface works with (key,properties) instead of `Entity` it's less obvious how to surface the mutation results.
If it were working with `Entity`, we could update its key accordingly (and eventually set some flags about version and conflicts if someone needs that).

**Comment by KevinGDialpad** [comment]
I ran into this as well. It would be nice to have Mutation and MutationResult classes, so we can just use the `commit()` method as a Python version of the commit endpoint.
I'm getting started on a PR for this.

**Comment by KevinGDialpad** [comment]
@TheKevJames Can we make a new release of datastore? 🙏

**Comment by TheKevJames** [comment]
@KevinGDialpad Ah, sorry about that, completely slipped my mind! Releasing this now as `gcloud-aio-datastore==6.2.0`
