### ISSUE TITLE
Update to gcloud-aio-auth==3.2.1 causes my download to hang in a specific circumstance 

### ISSUE THREAD

**Issue by nabobalis** [talkiq/gcloud-aio#172]
With gcloud-aio-auth==3.2.1 (https://github.com/talkiq/gcloud-aio/issues/167), the following code hangs for me within my async environment (I use fastapi):
```
from gcloud.aio.storage import Storage
    async with Storage(service_file=API_KEY) as storage: 
        bucket = storage.get_bucket(bucket_name) 
        blob = await bucket.get_blob(afile) 
        binary_data = await blob.download() 
```
(With `api_key`, `bucket_name`, `afile` as variables I have defined.
The part that hangs is `await blob.download()`.

If I kill the process I found `body = await resp.text(errors='replace')` as the last line in my traceback. So I reverted to gcloud-aio-auth==3.2.0 and my code runs again. 

I moved `body = await resp.text(errors='replace')` into the `except aiohttp.ClientResponseError:` block, my tests do not hang again. 

This code works if I run it in a python terminal. 

I am unsure how to write a reproducible test for this as I am unsure what the cause is. If it is the way I have written my async code or if this is a real bug.

Any help or advice would be really good!

**Comment by TheKevJames** [comment]
Huh, very interesting.

Could you try replacing `body = await resp.text(errors='replace')` with the following snippet (leaving it in the same place as in our 3.2.1 release):
```python
print('fetching resp.text')
if resp._body is None:
    print('reading into _body')
    await resp.read()
    print('done _body read')
print('grabbing encoding')
encoding = self.get_encoding()
print('got encoding: {}'.format(encoding))
print('decoding body')
body = self._body.decode(encoding, errors='replace')
```
and paste back the printed lines and let me know where it's hanging?

**Comment by TheKevJames** [comment]
If it happens to hang on the last line, please also try inserting the following before the last line:
```python
print('attempting to decode: {}'.format(resp._body))
```

**Comment by TheKevJames** [comment]
Also potentially helpful might be the full stack trace you described, if you have that around or can grab it again!

**Comment by nabobalis** [comment]
Thanks for the advice, I added the entire code block (I changed self to resp as that errored the code) and got this output:

```
fetching resp.text
reading into _body
done _body read
grabbing encoding
got encoding: utf-8
decoding body
attempting to decode: b'{REMOVED}'
fetching resp.text
reading into _body
done _body read
grabbing encoding
got encoding: utf-8
decoding body
attempting to decode: b'{REMOVED}'
fetching resp.text
reading into _body
done _body read
grabbing encoding
got encoding: utf-8
decoding body
attempting to decode: b'{REMOVED}'
fetching resp.text
reading into _body
done _body read
grabbing encoding
got encoding: utf-8
decoding body
attempting to decode: b'{REMOVED}'
fetching resp.text
reading into _body
done _body read
grabbing encoding
got encoding: utf-8
decoding body
attempting to decode: b'{REMOVED}'
fetching resp.text
reading into _body
done _body read
grabbing encoding
```
where it "waits" for a long time but does actually return unlike the original code.

As an aside, the file I get at the end is a 40MB NETCDF and getting its encoding really slows the download.

**Comment by TheKevJames** [comment]
Hmm, yeah, I basically just added print statements to the body of `resp.text()`. Looks like [resp.get_encoding()](https://github.com/aio-libs/aiohttp/blob/385b03ef21415d062886e1caab74eb5b93fdb887/aiohttp/client_reqrep.py#L940) might be the culprit, then...

Do you know the encoding of the relevant file? What happens if you replace:
```python
body = await resp.text(errors='replace')
```
with
```python
body = await resp.text(encoding='utf-8', errors='replace')
```
(or whatever the encoding should be for your data)?

**Comment by nabobalis** [comment]
The encoding is "utf-8" and adding `encoding='utf-8'` resolves my issue.

**Comment by TheKevJames** [comment]
So I dug a bit deeper into this -- looks like there might be something weird going on with the Google side of things here. Could you try running `await blob.download_metadata()` and checking the returned `contentType` value? If I understand right, if that's not set to something it can parse it falls back to this (much longer for large files) encoding detection logic.

If it turns out your value is set to something odd, perhaps you could change the metadata on Google's side? Clicking on "Edit Metadata" for a given GCS object should let you set this manually.

If it turns out you can fix the latency issues by setting the metadata correctly, that's probably enough for me to write up some warning docs, at the very least.

**Comment by nabobalis** [comment]
The `contentType` for the file:

```
{'kind': 'storage#object',
'contentType': 'application/x-netcdf',
'storageClass': 'STANDARD',
'size': '16649150'}
```

**Comment by TheKevJames** [comment]
Ah! Alright, that makes sense. So if you set your `contentType` to `'application/x-netcdf; charset=utf-8'`, you should be able to sidestep the issue. Looks like netcdf does not have a default charset defined, so `aiohttp` has to literally read the entire file and [guess by examining the entire file contents](https://github.com/chardet/chardet/blob/eb1a10a5d1b63bd9aefd1df9c669c298277e420b/chardet/__init__.py#L27) -- since your file is pretty big, this takes a long while. If you're sure about the charset you're using, setting this value explicitly should help prevent any other libs you're using from needing to guess :)

**Comment by TheKevJames** [comment]
([added the above info and some extra context to our docs](https://github.com/talkiq/gcloud-aio/commit/4740decd03c31e560683a842a4c6de7f0a9b3056))

**Comment by nabobalis** [comment]
Thanks I will about changing the metadata in my buckets. The only remaining question is, why is body called at the start of the function when it only needs to be evaluated if the try block errors?

**Comment by nabobalis** [comment]
As an extra note, I was looking at the aiohttp documentation and it mentioned doing `pip install aiohttp[speedups]` for some extra dependencies that seems to speed up the test (from 3 mins to about 30 seconds) with `gcloud-aio-auth==3.2.1` without changing the bucket metadata.

**Comment by TheKevJames** [comment]
It's an unfortunate `aiohttp` gotcha -- calling `resp.raise_for_status()` [consumes the response body](https://github.com/aio-libs/aiohttp/blob/385b03ef21415d062886e1caab74eb5b93fdb887/aiohttp/client_reqrep.py#L896) and thus prevents us from returning it later on. Since the Google APIs can return a whole lot of useful debugging info in the body, we need to grab it _before_ checking the error code to ensure that we can return it in the failure case. Maybe we should just re-write their `raise_for_status()` to avoid this...

`aiohttp[speedups]` is a good callout -- we don't want to have our library depend on it directly in case there are users who don't want the `speedups` extras, but you can always install them yourself, eg. by adding `aiohttp[speedups]` directly to your dependencies alongside `gcloud-aio`.

**Comment by TheKevJames** [comment]
Quick update: we ended up rewriting `raise_for_status()` as a part of `gcloud-aio-auth==3.4.0`, so any latency issues there should be resolved!
