### ISSUE TITLE
`_raise_for_status` addition creates unnecessary exception logs

### ISSUE THREAD

**Issue by xaocon** [talkiq/gcloud-aio#179]
`_raise_for_status` added in #126 and updated in #167 results in exceptions being logged for all results with a code >= 400. This probably isn't how all calls should be treated. For example, `blob_exists()` in storage calls `get_blob()` with an exception handler to to check for 404's and 410's. My logs are now littered with exceptions. I can't find any other affected methods with some quick grep foo but I don't know the code base all that well there could be other places.

**Comment by TheKevJames** [comment]
@xaocon yeah, that's a good point. Unfortunately, we've not come up with a good solution yet -- if we don't log the error before letting `aiohttp` raise any connection errors, then it swallows the respone object and makes debugging real issues impossible. That said, this comes with the downside you've come across -- even expected (to users) exceptions need to get logged in this case.

I'd really rather not try to go through and allowlist/denylist every given Google API to try to guess how users would expect the API to work (eg. whether to log errors for that route or not), especially since we're definitely likely to get a few wrong in that case (or run into cases where different users have different usecases). I'm open to options here, if anyone has thoughts on how we might be able to do this better!
