### ISSUE TITLE
Timeout for AioSession should be of type ClientTimeout

### ISSUE THREAD

**Issue by tinycogio** [talkiq/gcloud-aio#236]
The default ClientSession is being created with a timeout of 10 when aiohttp is expecting the timeout to be a ClientTimeout object.

## Stacktrace
```
AttributeError: 'int' object has no attribute 'total'
  File "gae_collector.py", line 549, in collector_post
    await asyncio.create_task(request.app['BQ_BUFFER'].flush_batches(batches_to_force_flush=batches_to_force_flush))
  File "<string>", line 21, in func_wrapper
    PYTHON_VERSION_INFO = sys.version_info
  File "bq_enqueue.py", line 153, in flush_batches
    await asyncio.gather(*tasks)
  File "<string>", line 21, in func_wrapper
    PYTHON_VERSION_INFO = sys.version_info
  File "bq_enqueue.py", line 200, in enqueue_upload_bq_cloud_task_aio
    return await self.gtask.create(task)
  File "/env/lib/python3.7/site-packages/gcloud/aio/taskqueue/queue.py", line 85, in create
    return await self._request('POST', url, json=body, session=session)
  File "backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/gcloud/aio/taskqueue/queue.py", line 67, in _request
    auto_raise_for_status=False, **kwargs)
  File "/env/lib/python3.7/site-packages/gcloud/aio/auth/session.py", line 135, in request
    **kwargs)
  File "aiohttp/client.py", line 404, in _request
    tm = TimeoutHandle(self._loop, real_timeout.total)
```

## Version
aiohttp==3.7.2
gcloud-aio-auth==3.4.3
Python 3.7

Offending line: https://github.com/talkiq/gcloud-aio/blob/f52be6bdd0fd41a4cd4a717ddc7ded99c02f57fe/auth/gcloud/aio/auth/session.py#L107

## Suggested fix:
```python
self._session = self._session or aiohttp.ClientSession(
                connector=connector, timeout=aiohttp.ClientTimeout(total=self._timeout))
```

## Conflicting code on aiohttp side
* https://github.com/aio-libs/aiohttp/blob/26504e08df7c64531c2610483d49e0af4b197be7/aiohttp/client.py#L211
* https://github.com/aio-libs/aiohttp/blob/26504e08df7c64531c2610483d49e0af4b197be7/aiohttp/client.py#L329
* (The if case that is being used when timeout is an int) https://github.com/aio-libs/aiohttp/blob/26504e08df7c64531c2610483d49e0af4b197be7/aiohttp/client.py#L386
* (Where error actually happens) https://github.com/aio-libs/aiohttp/blob/26504e08df7c64531c2610483d49e0af4b197be7/aiohttp/client.py#L389

aiohttp default timeout: https://github.com/aio-libs/aiohttp/blob/26504e08df7c64531c2610483d49e0af4b197be7/aiohttp/client.py#L161

**Comment by TheKevJames** [comment]
Huh, interesting, I would have expected https://github.com/aio-libs/aiohttp/blob/26504e08df7c64531c2610483d49e0af4b197be7/aiohttp/client.py#L383-L384 to set the value to a `ClientTimeout` instance in that case.

Either way, we've only been using a `float` to maintain support for aiohttp versions before v3.2. Since that's now three and a half years old, I think we can go ahead and drop support.

EDIT: I'm a fool, I've already dropped support for outdated `aiohttp` versions a while ago. My bad, should have updated to use `ClientTimeout` then, as well.

Solved in 36a5ee6a53aebb21bdafbfb10d42263c25eb19fb, will be included in the next `gcloud-aio-auth` release. Thanks for the report!
