### ISSUE TITLE
close aiohttp.ClientSession upon deconstruction

### ISSUE THREAD

**Issue by TheKevJames** [talkiq/gcloud-aio#33]
Anywhere we assign `self.session = aiohttp.ClientSession()`, we should probably close the session on cleanup with something like `def __del__(self): self.session.close()`

**Comment by JendaPlhak** [comment]
You most certainly should do that. As for now, it generates a lot of asyncio errors such as:
```2018-12-05 12:42:39 ERROR asyncio: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f695ac08198>
```

**Comment by TheKevJames** [comment]
Unfortunately, we've yet to find a good way to do this. See discussion in #50. Any suggestions would be greatly appreciated!

**Comment by mozbhearsum** [comment]
My workaround for this is to pass my own ClientSession in. It's inconvenient, but it works.

**Comment by TheKevJames** [comment]
This has now been solved! As of the following versions, any classes which implicitly create a session now can either be used as a context manager (which will close the session on leaving scope) or can have their `.close()` method called:
- `gcloud-aio-auth==3.1.0`
- `gcloud-aio-bigquery==3.4.0`
- `gcloud-aio-datastore==5.5.0`
- `gcloud-aio-kms==3.2.0`
- `gcloud-aio-storage==5.3.0`
- `gcloud-aio-taskqueue==4.1.0`

(thanks @elysium31 for submitting the code to kick this off!)

**Comment by burnpanck** [comment]
@TheKevJames Is there a list of classes which create sessions implicity? I use `gcloud.aio.storage.Storage` as an async context manager, but I still see these errors. Because of our code rules, we can't have uncaught exceptions, and so we use an event loop that tears down everything when encountering an exception. So we need to be able to guarantee that there are no "lost" sessions.
