### ISSUE TITLE
Create entity with excluded from indexes properties

### ISSUE THREAD

**Issue by umax** [talkiq/gcloud-aio#348]
Hi, team!

Please suggest what is a correct way to create entity with some properties excluded from indexes? I use this way but got error `NotImplementedError: <class 'gcloud.aio.datastore.value.Value'> is not a supported value type`.

```python
properties = {
    'active': True,
    'data' : Value(data, exclude_from_indexes=True),
}
key = Key(settings.GCLOUD_PROJECT_ID, [PathElement('MyEntity')])
await client.insert(key, properties)
```

Thank you!

**Comment by umax** [comment]
@KevinGDialpad  can you advise please?

**Comment by KevinGDialpad** [comment]
Hm, it seems to be a limitation of the library. insert() doesn't handle Value objects.

So the API endpoint that's used here is [commit](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit), which expects some Mutation objects. gcloud-aio creates them in [make_mutation](https://github.com/talkiq/gcloud-aio/blob/ffb33392339ebf1a87f4ca37b269ac8b26262b6a/datastore/gcloud/aio/datastore/datastore.py#L115-L129), but it's not expecting the `properties` param to contain Value objects.

I don't see why it shouldn't accept Values. Then it would create the mutation with `v.to_repr()` instead of `cls.value_kind(v).to_repr()`.

Let's see if there is a clean way to make that happen.

**Comment by TheKevJames** [comment]
@umax thanks for the bug report! @KevinGDialpad 's fix has been merged and released as [gcloud-aio-datastore v6.3.0](https://github.com/talkiq/gcloud-aio/releases/tag/datastore-6.3.0)

**Comment by umax** [comment]
Thank you @TheKevJames @KevinGDialpad !

**Comment by umax** [comment]
hi, @TheKevJames @KevinGDialpad 

The entity created, but I see in Google Admin UI that property still indexed:

```
    properties = {
        'cancelled': cancelled,
        'cancelled_order_data': Value(
            cancelled_order_data,
            exclude_from_indexes=True,
        ),
    }
    key = Key(settings.GCLOUD_PROJECT_ID, [PathElement('DeliveryOrder')])
    await _client.insert(key, properties)

    return key, properties
```

**Comment by umax** [comment]
Ok, when create entity, yes, field is not indexed. But when the field updated - it become indexed again.

**Comment by TheKevJames** [comment]
When you're updating the field, are you continuing to set `exclude_from_indexes`? If I understand the Google API correctly, each individual field is overwritten entirely on update, so for example if you wanted to do the following:
```python
    properties = {
        'cancelled_order_data': 'foobar',
    }
    key = Key(settings.GCLOUD_PROJECT_ID, [PathElement('DeliveryOrder'), 1234])
    await _client.update(key, properties)
```
You would be entirely replacing the old value of `cancelled_order_data` (ie. which includes the `exclude_from_indexes` setting) with the new `foobar` value. Instead, you would want to do:
```python
    properties = {
        'cancelled_order_data': Value('foobar', exclude_from_indexes=True),
    }
    key = Key(settings.GCLOUD_PROJECT_ID, [PathElement('DeliveryOrder'), 1234])
    await _client.update(key, properties)
```

**Comment by umax** [comment]
Thank you, @TheKevJames It's works using this way.
