### ISSUE TITLE
Auth failures are not surfaced with ADC

### ISSUE THREAD

**Issue by mbrancato** [talkiq/gcloud-aio#393]
If a user's ADC expire frequently, auth will fail. When using the pubsub subscriber helper, the only thing returned to the user is this:

https://github.com/talkiq/gcloud-aio/blob/5eff07d15a3e21f6a24ec905d2abfbab34ccf18a/pubsub/gcloud/aio/pubsub/subscriber.py#L416

On the backend, there is a backoff retry to auth, but if it fails 5 times, there is no indication to the user that auth is failing.

**Comment by TheKevJames** [comment]
@mbrancato thanks for the error report!

You should be able to get more debugging information from the previous log line; namely [this one](https://github.com/talkiq/gcloud-aio/blob/5eff07d15a3e21f6a24ec905d2abfbab34ccf18a/pubsub/gcloud/aio/pubsub/subscriber.py#L402) where we attach the exception to the log directly. Does this not include the auth failure message? It has for some of my test cases, but perhaps I've not tested the correct failure mode.

Alternatively, are you looking for a method of recovering? If so, you may be interested in [following the customization instructions](https://github.com/talkiq/gcloud-aio/tree/master/pubsub#customization) to change how the Token class does retries -- if you'd like it to act differently to eg. retry more frequently, you could add a retry handler to [`.get()`](https://github.com/talkiq/gcloud-aio/blob/36a5ee6a53aebb21bdafbfb10d42263c25eb19fb/auth/gcloud/aio/auth/token.py#L143), for example.

Otherwise, I'm curious why auth is failing in this case -- the token handler [should be generating a new token whenever the previous one starts to expire](https://github.com/talkiq/gcloud-aio/blob/36a5ee6a53aebb21bdafbfb10d42263c25eb19fb/auth/gcloud/aio/auth/token.py#L157-L163). Is this flow now working in your use-case?

**Comment by TheKevJames** [comment]
Closed as stale.
