### ISSUE TITLE
auth (Token):  raise exception when service_file is empty

### ISSUE THREAD

**Issue by awoimbee** [talkiq/gcloud-aio#427]
[Here is the culprit](https://github.com/talkiq/gcloud-aio/blob/ed4d0434e69e284488b9bb9026751a9c1fb757a1/auth/gcloud/aio/auth/token.py#L63).

Currently, an empty `service_file` is treated like if there was no `service_file`, this can cause issue when a bug causes this file to be empty. Currently `gcloud-aio` will ignore the `service-file` arguemnt and try to connect using internal gcloud compute endpoints, causing http 404.

**Comment by TheKevJames** [comment]
Hmm, that's an interesting case. Currently, that behaviour is somewhat intentional based on [this check](https://github.com/talkiq/gcloud-aio/blob/ed4d0434e69e284488b9bb9026751a9c1fb757a1/auth/gcloud/aio/auth/token.py#L85-L87). See the [original issue](https://github.com/talkiq/gcloud-aio/issues/61) for the reasoning. Basically, this amounts to wanting to match the behaviour of the google-auth library, to avoid confusing users who are switching between the two.

That said, it has been a while since we've audited the inner workings of the Google packages; if their behaviour has also changed (ie. such that they raise an error if you have an empty service file, even when that service file is _not_ explicitly passed to their library), we'd be happy to update our implementation accordingly!
