### ISSUE TITLE
auth(question): aiohttp session not closed 

### ISSUE THREAD

**Issue by JensMadsen** [talkiq/gcloud-aio#63]
auth.py:168

if user does not provide a session a session is created here, but as far as I can see the session is never closed? I think this cause errors in my code. 

My use case is instantiate a storage object without session and then use download later on passing a session. I can fix this by passing the constructor a session but in any case :-)

**Comment by TheKevJames** [comment]
Yes indeed, this is a known issue that has come up before in #50 and #33 -- be aware that the log entries are warnings rather than errors. We'd absolutely love to get this fixed -- I'm going to close this issue as a duplicate, but if you have any ideas or suggestions, please feel free to comment in #33!
